version: '3.4'
services:
  api:
    hostname: api
    container_name: api
    build:
        context: .
        dockerfile: ./src/api/Dockerfile
    ports:
        - "5000:80"
        - "5001:443"
    environment:
       - "UseInMemoryDatabase=true"
       - ASPNETCORE_ENVIRONMENT=Development
       - JwtAppSettings:Secret=http://localhost:3000
       - JwtAppSettings:ValidAudience=http://localhost:3000
       - JwtAppSettings:ValidIssuer=http://localhost:3000
       - JwtAppSettings:SessionMinutes=20
       - Client_Url=*
    restart: on-failure
    volumes:
        - logs-vol:/app/logs/
volumes:
    logs-vol:
